server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Redirect old anker install path to ikno
    location = /anker/install.sh {
        return 301 /ikno/install.sh;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
